// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzqXmHSiv177h5s2TjXbEydogtSth47y4',
    appId: '1:689993267294:web:b2930e017e1acc55e31ccf',
    messagingSenderId: '689993267294',
    projectId: 'storageapp-20dfa',
    authDomain: 'storageapp-20dfa.firebaseapp.com',
    storageBucket: 'storageapp-20dfa.firebasestorage.app',
    measurementId: 'G-WDGR2ED815',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnLRNAejVXd3up6F4ml2EYVWbzx9emEFY',
    appId: '1:689993267294:android:b25b54faf0638c86e31ccf',
    messagingSenderId: '689993267294',
    projectId: 'storageapp-20dfa',
    storageBucket: 'storageapp-20dfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPG8VwLHvNQ29YHl7MFh60qKMXBlUS_Y0',
    appId: '1:689993267294:ios:f4039eebbefb8b1ae31ccf',
    messagingSenderId: '689993267294',
    projectId: 'storageapp-20dfa',
    storageBucket: 'storageapp-20dfa.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPG8VwLHvNQ29YHl7MFh60qKMXBlUS_Y0',
    appId: '1:689993267294:ios:f4039eebbefb8b1ae31ccf',
    messagingSenderId: '689993267294',
    projectId: 'storageapp-20dfa',
    storageBucket: 'storageapp-20dfa.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzqXmHSiv177h5s2TjXbEydogtSth47y4',
    appId: '1:689993267294:web:ef7e874528d311d4e31ccf',
    messagingSenderId: '689993267294',
    projectId: 'storageapp-20dfa',
    authDomain: 'storageapp-20dfa.firebaseapp.com',
    storageBucket: 'storageapp-20dfa.firebasestorage.app',
    measurementId: 'G-DEZGMX7JCX',
  );
}
